version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ramzidb
      POSTGRES_USER: ramzi
      POSTGRES_PASSWORD: ramzi
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ramzibouzaiene00@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ramzi
    ports:
      - "5050:80"
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge

volumes:
  pg-data: