server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'ramzi'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'ramzi'
    driverClassName: org.postgresql.Driver
    jpa:
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.format_sql: 'true'
        hibernate.ddl-auto: update
