name: GitHub Actions Execution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Build with Maven
        run: |
          mvn clean install --batch-mode --errors

      - name: Run Tests
        run: |
          mvn test --batch-mode --errors

      - name: Package Artifact
        run: mvn package --batch-mode --errors
        if: success()

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target/
        if: success()
